# Generated by Django 4.2.16 on 2025-01-17 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0126_remoteartifact_failed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='upstreampulp',
            name='content_origin',
            field=models.TextField(null=True),
        ),
    ]
